In [1]:
import pandas as pd

# Folder attack_logs
- Info about executed attacks

The CIDDS-001 data set was captured over a period of four weeks and contains nearly **32 millions flows**. 

Thereof, about 31 millions flows were captured within the OpenStack environment. About 0.7 million flows were captured at the external server.

**92 attacks**.  
**70 attacks** were executed within the **OpenStack** environment and 
**22 attacks** targeted the external server.

In [2]:
# both contain source IP; start- & end time as well as short description of attacks
# attacks against external server
attack_logs_extern = pd.read_csv('data/CIDDS-001/attack_logs/attack_logs_extern.csv')
# attacks executed in the OpenStack environment
attack_logs_intern = pd.read_csv('data/CIDDS-001/attack_logs/attack_logs_intern.csv')

In [3]:
attack_logs_extern

,IP,start,end,activity,activityID,description
0,ATTACKER1,2017-03-23 09:46:00.000000,2017-03-23 09:48:00.000000,portScan,1,---
1,ATTACKER1,2017-03-23 10:14:00.000000,2017-03-23 10:30:00.000000,portScan,2,---
2,ATTACKER1,2017-03-23 11:33:00.000000,2017-03-23 12:00:00.000000,bruteForce,3,---
3,ATTACKER1,2017-03-23 12:43:00.000000,2017-03-23 12:48:00.000000,bruteForce,4,---
4,ATTACKER1,2017-03-23 13:36:00.000000,2017-03-23 13:42:00.000000,bruteForce,5,---
5,ATTACKER1,2017-03-23 18:03:00.000000,2017-03-23 18:07:00.000000,bruteForce,6,---
6,ATTACKER2,2017-04-08 11:21:00.000000,2017-04-08 12:09:00.000000,portScan,7,nmap args: -sS -T 2
7,ATTACKER2,2017-04-08 12:19:00.000000,2017-04-08 12:26:00.000000,bruteForce,8,100 passwords
8,ATTACKER2,2017-04-08 12:32:00.000000,2017-04-08 12:43:00.000000,bruteForce,9,100 passwords
9,ATTACKER2,2017-04-08 13:14:00.000000,2017-04-08 13:40:00.000000,portScan,10,nmap args: -sU -T 2
10,ATTACKER2,2017-04-08 15:00:00.000000,2017-04-08 15:40:00.000000,bruteForce,11,100 passwords
11,ATTACKER1,2017-04-08 15:43:00.000000,2017-04-08 16:12:00.000000,portScan,12,nmap args: -sU -T 2
12,ATTACKER1,2017-04-08 16:32:00.000000,2017-04-08 16:47:00.000000,bruteForce,13,100 passwords
13,ATTACKER1,2017-04-08 16:52:00.000000,2017-04-08 16:58:00.000000,bruteForce,14,100 passwords
14,ATTACKER1,2017-04-08 17:08:00.000000,2017-04-08 17:15:00.000000,portScan,15,nmap args: -sS -T 2
15,ATTACKER1,2017-04-10 09:22:00.000000,2017-04-10 10:34:00.000000,portScan,16,nmap args: -sS -T 2
16,ATTACKER1,2017-04-10 11:11:00.000000,2017-04-10 11:50:00.000000,bruteForce,17,100 passwords
17,ATTACKER1,2017-04-10 12:44:00.000000,2017-04-10 13:05:00.000000,bruteForce,18,100 passwords
18,ATTACKER3,2017-04-15 13:29:00.000000,2017-04-15 13:44:00.000000,portScan,19,nmap args: -sS -T 2
19,ATTACKER3,2017-04-15 14:00:00.000000,2017-04-15 14:20:00.000000,bruteForce,20,100 passwords
20,ATTACKER3,2017-04-15 14:35:00.000000,2017-04-15 14:38:00.000000,bruteForce,21,20 passwords
21,ATTACKER3,2017-04-15 14:53:00.000000,2017-04-15 14:56:00.000000,bruteForce,22,20 passwords

In [4]:
attack_logs_intern

,IP,start,end,duration,activity,activityID,errorcode,description
0,192.168.220.16,2017-03-14 16:05:30.148959,2017-03-15 09:08:40.326217,17:03:10.537554,portScan,1,0,nmap args: -sS -T 1
1,192.168.220.16,2017-03-15 09:19:34.419360,2017-03-15 12:40:08.318166,3:20:34.898806,portScan,2,0,nmap args: -sS -T 1
2,192.168.220.16,2017-03-15 13:07:57.209295,2017-03-15 13:08:22.732685,0:00:25.523390,dos,3,0,---
3,192.168.220.16,2017-03-15 13:41:35.876926,2017-03-15 13:43:42.684341,0:02:06.807415,dos,4,0,---
4,192.168.220.16,2017-03-15 14:15:43.315230,2017-03-15 14:21:46.397800,0:06:03.082570,portScan,5,0,nmap args: -sS -T 3
...,...,...,...,...,...,...,...,...
65,192.168.220.15,2017-03-27 09:42:21.858684,2017-03-27 09:52:55.176393,0:10:33.317709,pingScan,66,0,nmap args: -n -sP -PE -T 2
66,192.168.220.15,2017-03-27 09:58:12.215757,2017-03-28 06:58:21.707589,21:00:09.491832,portScan,67,0,nmap args: -sS -T 1
67,192.168.220.15,2017-03-28 07:08:01.815066,2017-03-28 18:20:49.400941,11:12:47.585875,portScan,68,0,nmap args: -sS -T 1
68,192.168.220.15,2017-03-28 18:29:41.466911,2017-03-28 18:46:55.025260,0:17:13.558349,pingScan,69,0,nmap args: -n -sP -PE -T 1
69,192.168.220.15,2017-03-28 18:55:13.427074,2017-03-28 18:55:27.548919,0:00:14.121845,bruteForce,70,0,192.168.100.2

# Folder client_confs
- the configurations of different clients as conf files (probably most similar to an instantiated object) 
- config files with which the normal user behaviour of the clients is executed; IP-Address in the name allows to map configuration to the corresponding client 
- The config files controlls (among other things) the user behaviour of the client & it's working hours; the user behaviour is defined through the probabilities of the client's activities

# Folder client_logs
- The logs of different clients as .log files; internally they look like a .csv file 
- A csv for each client 
- The Python script that controls the user behaviour records here the activities of the clients 
- Allows to understand, which client activities caused network traffic

In [5]:
client_1 = pd.read_csv('data/CIDDS-001/client_logs/192.168.220.6.log')

In [6]:
client_1

,IP,start,end,duration,activity,activityID,errorcode,description
0,192.168.220.6,2017-03-15 06:09:40.603658,2017-03-15 06:10:05.742381,0:00:25.138723,printing,863,0,---
1,192.168.220.6,2017-03-15 06:10:05.750113,2017-03-15 06:40:18.819345,0:30:13.069232,meeting,864,0,---
2,192.168.220.6,2017-03-15 06:40:18.827617,2017-03-15 06:42:26.928649,0:02:08.101032,break,865,0,---
3,192.168.220.6,2017-03-15 06:42:26.937050,2017-03-15 06:45:03.393192,0:02:36.456142,private,866,0,---
4,192.168.220.6,2017-03-15 06:45:03.399745,2017-03-15 06:45:38.659627,0:00:35.259882,browsing,867,0,---
...,...,...,...,...,...,...,...,...
1158,192.168.220.6,2017-04-17 15:11:35.147388,2017-04-17 15:54:45.211617,0:43:10.064229,meeting,2021,0,---
1159,192.168.220.6,2017-04-17 15:54:45.218765,2017-04-17 15:55:36.089553,0:00:50.870788,mailing,2022,0,---
1160,192.168.220.6,2017-04-17 15:55:36.095218,2017-04-17 15:56:00.125712,0:00:24.030494,browsing,2023,0,---
1161,192.168.220.6,2017-04-17 15:56:00.132560,2017-04-17 15:59:52.358765,0:03:52.226205,browsing,2024,0,---
1162,192.168.220.6,2017-04-17 15:59:52.364182,2017-04-17 17:39:16.444776,1:39:24.080594,meeting,2025,0,---

# Folder traffic
- "Captured flow-based network traffic in unidirectional NetFlow format"
- last part of file name => in which week was the traffic recorded
## ExternalServer
- traffic recorded on the external server

In [7]:
external_server_week1 = pd.read_csv('data/CIDDS-001/traffic/ExternalServer/CIDDS-001-external-week1.csv')

In [8]:
external_server_week1

,Date first seen,Duration,Proto,Src IP Addr,Src Pt,Dst IP Addr,Dst Pt,Packets,Bytes,Flows,Flags,Tos,class,attackType,attackID,attackDescription
0,2017-03-14 17:43:57.172,81412.697,TCP,EXT_SERVER,8082,OPENSTACK_NET,56978.0,3057,2.1 M,1,.AP...,0,normal,---,---,---
1,2017-03-14 17:43:57.172,81412.697,TCP,OPENSTACK_NET,56978,EXT_SERVER,8082.0,4748,2.5 M,1,.AP...,0,normal,---,---,---
2,2017-03-14 17:43:26.135,81504.787,TCP,EXT_SERVER,8082,OPENSTACK_NET,56979.0,8639,9.1 M,1,.AP...,0,normal,---,---,---
3,2017-03-14 17:43:26.135,81504.787,TCP,OPENSTACK_NET,56979,EXT_SERVER,8082.0,12024,10.3 M,1,.AP...,0,normal,---,---,---
4,2017-03-14 18:17:09.005,82100.692,TCP,EXT_SERVER,8082,OPENSTACK_NET,51649.0,11012,27.2 M,1,.AP.S.,0,normal,---,---,---
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172833,2017-03-16 11:42:01.298,518988.907,TCP,OPENSTACK_NET,49939,EXT_SERVER,8082.0,17446,10.6 M,1,.APRS.,0,normal,---,---,---
172834,2017-03-16 12:10:17.340,517292.865,TCP,EXT_SERVER,8082,OPENSTACK_NET,58749.0,9406,3.4 M,1,.AP.S.,0,normal,---,---,---
172835,2017-03-16 12:10:17.340,517292.865,TCP,OPENSTACK_NET,58749,EXT_SERVER,8082.0,15510,10.3 M,1,.APRS.,0,normal,---,---,---
172836,2017-03-16 15:52:58.342,503931.863,TCP,EXT_SERVER,8082,OPENSTACK_NET,62605.0,13362,5.2 M,1,.AP.S.,0,normal,---,---,---
172837,2017-03-16 15:52:58.342,503931.863,TCP,OPENSTACK_NET,62605,EXT_SERVER,8082.0,20262,17.8 M,1,.APRS.,0,normal,---,---,---

## OpenStack
- Traffic of internal origin

In [9]:
open_stack_week1 = pd.read_csv('data/CIDDS-001/traffic/OpenStack/CIDDS-001-internal-week1.csv')

/home/ursina/anaconda3/envs/project_ml/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
open_stack_week1

,Date first seen,Duration,Proto,Src IP Addr,Src Pt,Dst IP Addr,Dst Pt,Packets,Bytes,Flows,Flags,Tos,class,attackType,attackID,attackDescription
0,2017-03-15 00:01:16.632,0.000,TCP,192.168.100.5,445,192.168.220.16,58844.0,1,108,1,.AP...,0,normal,---,---,---
1,2017-03-15 00:01:16.552,0.000,TCP,192.168.100.5,445,192.168.220.15,48888.0,1,108,1,.AP...,0,normal,---,---,---
2,2017-03-15 00:01:16.551,0.004,TCP,192.168.220.15,48888,192.168.100.5,445.0,2,174,1,.AP...,0,normal,---,---,---
3,2017-03-15 00:01:16.631,0.004,TCP,192.168.220.16,58844,192.168.100.5,445.0,2,174,1,.AP...,0,normal,---,---,---
4,2017-03-15 00:01:16.552,0.000,TCP,192.168.100.5,445,192.168.220.15,48888.0,1,108,1,.AP...,0,normal,---,---,---
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8451515,2017-03-21 23:59:56.083,0.248,TCP,192.168.200.8,62605,EXT_SERVER,8082.0,2,319,1,.AP...,0,normal,---,---,---
8451516,2017-03-21 23:59:57.037,0.000,TCP,10179_174,443,192.168.210.5,51433.0,1,54,1,.A....,32,normal,---,---,---
8451517,2017-03-21 23:59:56.920,0.000,TCP,192.168.210.5,51433,10179_174,443.0,1,55,1,.A....,0,normal,---,---,---
8451518,2017-03-21 23:59:58.299,0.000,TCP,192.168.100.5,445,192.168.220.6,56281.0,1,108,1,.AP...,0,normal,---,---,---
8451519,2017-03-21 23:59:58.298,0.002,TCP,192.168.220.6,56281,192.168.100.5,445.0,2,174,1,.AP...,0,normal,---,---,---

![](graphics/attacks_table.jpeg)